builds:
  - binary: go-build-template
    main: cmd/go-build-template/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
release:
  github:
    owner: sythe21
    name: go-build-template
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - README.md
